{{- range $collectorName := include "collectors.list.enabled" . | fromYamlArray }}
{{- include "crdValidation" $ }}
{{- $values := (deepCopy $ | merge (dict "collectorName" $collectorName)) }}
{{- $alloyValues := (include "collector.alloy.values" $values | fromYaml) | merge (dict "nameOverride" $collectorName) }}
{{- $alloySpec := include "collector.alloy.valuesToSpec" $alloyValues }}
---
apiVersion: collectors.grafana.com/v1alpha1
kind: Alloy
metadata:
  name: {{ include "collector.alloy.fullname" $values }}
  namespace: {{ $.Release.Namespace }}
  {{- if and (get $.Values "alloy-operator").deploy (get $.Values "alloy-operator").waitForReadiness }}
  annotations:
    "helm.sh/hook-weight": "10"
  {{- end }}
spec:{{ $alloySpec | trim | nindent 2 }}
{{- end }}
