---
name: Upload Telemetry
# yamllint disable-line rule:truthy
on:
  workflow_run:
    workflows: ["Unit Test"]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  upload-telemetry:
    name: Upload Telemetry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: grafana/hackathon-12-action-stat@latest
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          telemetry-url: https://otlp-gateway-prod-us-west-0.grafana.net/otlp
          telemetry-username: ${{ secrets.GC_TELEMETRY_DATA_UPLOAD_OTLP_USERNAME }}
          telemetry-password: ${{ secrets.GC_TELEMETRY_DATA_UPLOAD_OTLP_PASSWORD }}
