---
name: Upload Telemetry
# yamllint disable-line rule:truthy
on:
  workflow_run:
    workflows: ["Unit Test", "ReviewDog"]
    types:
      - completed

jobs:

  upload-telemetry:
    name: Upload Telemetry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Upload telemetry
        uses: grafana/hackathon-12-action-stat@v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          telemetry-url: https://otlp-gateway-prod-us-west-0.grafana.net/otlp
          telemetry-username: ${{ secrets.GC_TELEMETRY_DATA_UPLOAD_OTLP_USERNAME }}
          telemetry-password: ${{ secrets.GC_TELEMETRY_DATA_UPLOAD_OTLP_PASSWORD }}
          workflow-run-id: ${{ github.event.workflow_run.id }}
